#!/bin/bash

##############################################################################
## FUNCTION: HELP
##############################################################################

function help {
    echo "

        Usage: ${0} -1234567adlvh

        -1 speed up terminal : move ASL and plist files to DeskDrawer trash (dated)
	-2 declutter mac Desktop : move Mac Desktop contents to DeskDrawer (dated)
	-3 declutter mac Downloads : move Mac downloads to DeskDrawer (dated)
	-4 declutter mac trash : move Mac trash contents to DeskDrawer trash (dated)
	-5 declutter Caches :  move Mac Caches contents to DeskDrawer trash (dated)
	-6 Free up RAM
	-7 Reindex Spotlight
	-a All / Auto : Run all previous steps.
	-d Get disk space used by current directory.
	-l Loop over sub-directories in current directory, and get disk space used by each.
	-v View DeskDrawer in Finder

"
}

##############################################################################
## TRIGGER HELP IF NO ARGS
##############################################################################
if [ $# -eq 0 ]; then help; exit; fi



##############################################################################
## PATH VAR HANDLING
##############################################################################
MAIN=$( dirname ${0} )
BIN=${MAIN}/bin
export PATH=${MAIN}:${BIN}:${PATH}


##############################################################################
## DEFAULTS
##############################################################################
HELP=false
RUNTM=false # Terminal speed up
RUNDT=false # Desktop clean
RUNDN=false # Downloads clean
RUNMT=false # Mac Trash clean
RUNCS=false # Caches clean
RUNRM=false # Free up RAM
RUNSL=false # SpotLight reindex
RUNDU=false # Disk usage check
RUNDL=false # Disk usage loop
RUNVW=false # View DeskDrawer
RUN00=false # Empty DeskDrawer Trash

##############################################################################
## GET OPTS
##############################################################################
while getopts "1234567adlvh" arg; do
    case $arg in
	1) RUNTM=true ;;
	2) RUNDT=true ;;
	3) RUNDN=true ;;
	4) RUNMT=true ;;
	5) RUNCS=true ;;
	6) RUNRM=true ;;
	7) RUNSL=true ;;
	a) RUNTM=true ; RUNDT=true ; RUNDN=true ; RUNMT=true ; RUNCS=true ; RUNRM=true ; RUNSL=true ; RUNVW=true ; RUNDL=true ;;
	d) RUNDU=true ;;
	l) RUNDL=true ;;
	v) RUNVW=true ;;
	0) RUN00=true ;;
        h) HELP=true;;
        *) help; exit;;
    esac
done



##############################################################################
## DEBUG CODE
##############################################################################
# for VAR in RUNTM RUNDT RUNDN RUNMT RUNCS RUNRM RUNSL RUNTM RUNDU RUNDL RUNVW RUN00 HELP ; do echo ${VAR} ${!VAR} ; done


##############################################################################
## TRIGGER HELP IF OPTED FOR
##############################################################################
if ${HELP}; then help; exit; fi


##############################################################################
## PROCESS ARGS WHERE NECESSARY
##############################################################################


##############################################################################
## EXPORTS IF ANY
##############################################################################


##############################################################################
## RUN PIPELINE
##############################################################################

if $RUNTM ; then speedUpMyTerminal ; fi
if $RUNDT ; then declutterMyDesktop ; fi
if $RUNDN ; then declutterMacDownloads ; fi
if $RUNMT ; then declutterMacTrash ; fi
if $RUNCS ; then cleanUpMyCaches ; fi
if $RUNRM ; then freeUpMyRAM ; fi
if $RUNSL ; then rebuildSpotlightIndex ; fi
if $RUNVW ; then viewDeskDrawer ; fi
if $RUNDL ; then diskUsageThisDirAndAllSubDirLoop ; fi
if $RUNDU ; then diskUsageThisDirAndAllSubDir ; fi
if $RUN00 ; then emptyMyTrash ; fi

